web/router.ex
defmodule Appli.Router do
  use Appli.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Appli do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/papers", PapersController, :index
    resources "/signatures", SignatureController
    # resources "/signatures_admin", SignatureAdminController
    resources "/.well-known/acme-challenge", WellknowController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Appli do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Appli.LayoutView do
  use Appli.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Le Vinolien!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/social-share-kit.css") %>">
  </head>

  <body>
		<div class="ssk-sticky ssk-left ssk-center ssk-lg">
			<a href="" class="ssk ssk-facebook"></a>
			<a href="" class="ssk ssk-twitter"></a>
			<a href="" class="ssk ssk-google-plus"></a>
			<a href="" class="ssk ssk-tumblr"></a>
			<a href="" class="ssk ssk-email"></a>
		</div>
    <div class="container">
      <header>
        <div>
          <a href="<%= page_path(@conn, :index) %>">
            <img src="/images/LeVinolienLogo.png" alt="Responsive image" style="display: block; margin: 0 auto; text-align:center; max-width:80%">
          </a>
        </div>
        <nav role="navigation">
          <ul class="nav nav-pills">
            <li>
              <a href="<%= signature_path(@conn, :new) %>">Signer la petition</a>
            </li>
            <li>
              <a href="<%= papers_path(@conn, :index) %>">Petitions Papiers</a>
            </li>
          </ul>
        </nav>
        <div>
          <img src="/images/ecole_vineuil.jpg" alt="Responsive image" style="display: block; margin: 0 auto; text-align:center; max-width:60%">
        </div>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/social-share-kit.min.js") %>"></script>
		<script type="text/javascript">

				// Init Social Share Kit
				SocialShareKit.init({
						url: 'http://www.levinolien.fr',
            text: 'Sauvons l\'ecole de Vineuil St Firmin, signer notre petition',
						twitter: {
								title: 'Le vinolien'
						},
						onBeforeOpen: function(targetElement, network, paramsObj){
								console.log(arguments);
						},
						onOpen: function(targetElement, network, url, popupWindow){
								console.log(arguments);
						},
						onClose: function(targetElement, network, url, popupWindow){
								console.log(arguments);
						}
				});
		</script>
  </body>
</html>